export const ResourceName = {
  agents: "agents",
  agentRuntimes: "agentRuntimes",
  filesystem: "filesystem",
  operations: "operations",
  pipelines: "pipelines",
  jobs: "jobs",
  githubProjects: "githubProjects",
  skills: "skills",
  skillDraftOperations: "skillDraftOperations",
  skillAnalyses: "skillAnalyses",
  distillations: "distillations",
  refinements: "refinements",
  settings: "settings",
  operationOutputItemTemplates: "operationOutputItemTemplates",
} as const;
