import { beforeEach, describe, expect, it, vi } from "vitest";
import type { DataProvider } from "@refinedev/core";
import { createMaterializeGeneratedPipeline } from "./materializeGeneratedPipeline";
import type { PipelineAgentSessionsClient } from "./pipelineAgentSessionsClient";

const mockGetGeneratedPipelineMaterialization = vi.fn();
const mockGetOne = vi.fn();
const mockCreate = vi.fn();

const client = {
  getGeneratedPipelineMaterialization: mockGetGeneratedPipelineMaterialization,
} as unknown as PipelineAgentSessionsClient;
const dataProvider = {
  create: mockCreate,
  getOne: mockGetOne,
} as unknown as DataProvider;

const materializeGeneratedPipeline = createMaterializeGeneratedPipeline({ client, dataProvider });

describe("materializeGeneratedPipeline", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockGetGeneratedPipelineMaterialization.mockResolvedValue({
      operations: [
        {
          id: "operation-1",
          name: "Generated operation",
          description: "Generated by the agent",
          config: { executor: { type: "agent", prompt: "Return OK" }, inputs: [], outputs: [] },
          acceptedObjectTypes: ["prompt"],
        },
      ],
      pipeline: {
        id: "pipeline-1",
        name: "Generated pipeline",
        description: "",
        sharedContext: "",
        tags: ["agent-generated"],
        timeoutMs: null,
        nodes: [],
        edges: [],
        createdAt: new Date("2026-08-10T00:00:00.000Z"),
        updatedAt: new Date("2026-08-10T00:00:00.000Z"),
      },
    });
    mockGetOne.mockResolvedValue({ data: null });
    mockCreate
      .mockResolvedValueOnce({ data: { id: "operation-1" } })
      .mockResolvedValueOnce({ data: { id: "pipeline-1" } });
  });

  it("copies the generated operation and pipeline into the app data store", async () => {
    await expect(materializeGeneratedPipeline("pipeline-1")).resolves.toBe("pipeline-1");

    expect(mockGetGeneratedPipelineMaterialization).toHaveBeenCalledWith("pipeline-1");
    expect(mockCreate).toHaveBeenNthCalledWith(1, {
      resource: "operations",
      variables: expect.objectContaining({ id: "operation-1" }),
    });
    expect(mockCreate).toHaveBeenNthCalledWith(2, {
      resource: "pipelines",
      variables: expect.not.objectContaining({ createdAt: expect.anything() }),
    });
  });

  it("keeps an existing local operation and only creates the pipeline", async () => {
    mockGetOne
      .mockResolvedValueOnce({ data: null })
      .mockResolvedValueOnce({ data: { id: "operation-1" } });
    mockCreate.mockReset();
    mockCreate.mockResolvedValueOnce({ data: { id: "pipeline-1" } });

    await materializeGeneratedPipeline("pipeline-1");

    expect(mockCreate).toHaveBeenCalledTimes(1);
    expect(mockCreate).toHaveBeenCalledWith({
      resource: "pipelines",
      variables: expect.objectContaining({ id: "pipeline-1" }),
    });
  });

  it("assigns an Agent-generated pipeline to the active project", async () => {
    await materializeGeneratedPipeline("pipeline-1", "project-1");

    expect(mockCreate).toHaveBeenNthCalledWith(2, {
      resource: "pipelines",
      variables: expect.objectContaining({
        id: "pipeline-1",
        projectId: "project-1",
      }),
    });
  });

  it("returns an already materialized pipeline without creating a duplicate", async () => {
    mockGetOne.mockResolvedValueOnce({ data: { id: "pipeline-1" } });
    mockCreate.mockReset();

    await expect(materializeGeneratedPipeline("pipeline-1")).resolves.toBe("pipeline-1");
    expect(mockCreate).not.toHaveBeenCalled();
  });
});
