import { RuntimeAdapterManifestSchema, type RuntimeAdapterManifest } from "@repo/schemas";

const manifests = [
  {
    runtime: "claude-code",
    displayName: "Claude Code",
    supportLevel: "supported",
    binaries: ["claude"],
    versionArgs: ["--version"],
    streamFormat: "claude-stream-json",
    capabilities: {
      textStreaming: "delta",
      thinking: true,
      toolEvents: true,
      usage: true,
      cancellation: "none",
      resume: "cli",
      mcpInjection: "config",
      imageInput: false,
    },
  },
  {
    runtime: "codex",
    displayName: "Codex CLI",
    supportLevel: "supported",
    binaries: ["codex"],
    versionArgs: ["--version"],
    streamFormat: "json-event-stream",
    capabilities: {
      textStreaming: "message",
      thinking: true,
      toolEvents: true,
      usage: true,
      cancellation: "signal",
      resume: "session",
      mcpInjection: "config",
      imageInput: false,
    },
  },
  {
    runtime: "hermes",
    displayName: "Hermes Agent",
    supportLevel: "supported",
    binaries: ["hermes"],
    versionArgs: ["--version"],
    streamFormat: "acp-json-rpc",
    capabilities: {
      textStreaming: "delta",
      thinking: true,
      toolEvents: true,
      usage: true,
      cancellation: "protocol",
      resume: "protocol",
      mcpInjection: "protocol",
      imageInput: false,
    },
  },
  {
    runtime: "mastra",
    displayName: "Mastra",
    supportLevel: "supported",
    binaries: ["mastra"],
    versionArgs: ["--version"],
    streamFormat: "plain",
    capabilities: {
      textStreaming: "terminal",
      thinking: false,
      toolEvents: false,
      usage: true,
      cancellation: "none",
      resume: "none",
      mcpInjection: "none",
      imageInput: true,
    },
  },
  {
    runtime: "openclaw",
    displayName: "OpenClaw",
    supportLevel: "supported",
    binaries: ["openclaw"],
    versionArgs: ["--version"],
    streamFormat: "jsonl",
    capabilities: {
      textStreaming: "terminal",
      thinking: false,
      toolEvents: false,
      usage: false,
      cancellation: "none",
      resume: "session",
      mcpInjection: "none",
      imageInput: false,
    },
  },
  {
    runtime: "pi-agent",
    displayName: "Pi Agent",
    supportLevel: "supported",
    binaries: ["pi"],
    versionArgs: ["--version"],
    streamFormat: "pi-rpc",
    capabilities: {
      textStreaming: "delta",
      thinking: true,
      toolEvents: true,
      usage: true,
      cancellation: "protocol",
      resume: "session",
      mcpInjection: "none",
      imageInput: true,
    },
  },
  {
    runtime: "opencode",
    displayName: "OpenCode",
    supportLevel: "supported",
    binaries: ["opencode", "opencode-cli"],
    versionArgs: ["--version"],
    streamFormat: "json-event-stream",
    capabilities: {
      textStreaming: "delta",
      thinking: false,
      toolEvents: true,
      usage: true,
      cancellation: "signal",
      resume: "cli",
      mcpInjection: "config",
      imageInput: false,
    },
  },
  {
    runtime: "kimi-code",
    displayName: "Kimi CLI",
    supportLevel: "supported",
    binaries: ["kimi"],
    versionArgs: ["--version"],
    streamFormat: "acp-json-rpc",
    capabilities: {
      textStreaming: "delta",
      thinking: true,
      toolEvents: true,
      usage: true,
      cancellation: "protocol",
      resume: "protocol",
      mcpInjection: "protocol",
      imageInput: false,
    },
  },
  {
    runtime: "deepseek-harness",
    displayName: "DeepSeek Harness",
    supportLevel: "experimental",
    binaries: ["dsh"],
    versionArgs: ["--version"],
    streamFormat: "dsh-profile-jsonl",
    capabilities: {
      textStreaming: "delta",
      thinking: true,
      toolEvents: true,
      usage: true,
      cancellation: "protocol",
      resume: "protocol",
      mcpInjection: "protocol",
      imageInput: false,
    },
    setupCommand: ["ordine", "agent", "setup", "deepseek-harness"],
    diagnostic: "Requires a compatible user-installed dsh profile before execution.",
  },
  {
    runtime: "mistral-vibe",
    displayName: "Mistral Vibe CLI",
    supportLevel: "supported",
    binaries: ["vibe-acp", "vibe"],
    versionArgs: ["--version"],
    streamFormat: "acp-json-rpc",
    capabilities: {
      textStreaming: "delta",
      thinking: true,
      toolEvents: true,
      usage: true,
      cancellation: "protocol",
      resume: "protocol",
      mcpInjection: "protocol",
      imageInput: false,
    },
    diagnostic: "Requires an ACP-capable Vibe CLI build.",
  },
  {
    runtime: "deepseek-reasonix",
    displayName: "DeepSeek Reasonix",
    supportLevel: "supported",
    binaries: ["reasonix", "dsnix"],
    versionArgs: ["--version"],
    streamFormat: "acp-json-rpc",
    capabilities: {
      textStreaming: "delta",
      thinking: true,
      toolEvents: true,
      usage: true,
      cancellation: "protocol",
      resume: "protocol",
      mcpInjection: "protocol",
      imageInput: false,
    },
  },
  {
    runtime: "kiro",
    displayName: "Kiro CLI",
    supportLevel: "supported",
    binaries: ["kiro-cli"],
    versionArgs: ["--version"],
    streamFormat: "acp-json-rpc",
    capabilities: {
      textStreaming: "delta",
      thinking: true,
      toolEvents: true,
      usage: true,
      cancellation: "protocol",
      resume: "protocol",
      mcpInjection: "protocol",
      imageInput: false,
    },
  },
  {
    runtime: "trae",
    displayName: "Trae CLI",
    supportLevel: "supported",
    binaries: ["traecli"],
    versionArgs: ["--version"],
    streamFormat: "acp-json-rpc",
    capabilities: {
      textStreaming: "delta",
      thinking: true,
      toolEvents: true,
      usage: true,
      cancellation: "protocol",
      resume: "protocol",
      mcpInjection: "protocol",
      imageInput: false,
    },
  },
] as const;

export const RUNTIME_MANIFESTS: readonly RuntimeAdapterManifest[] = manifests.map((manifest) =>
  RuntimeAdapterManifestSchema.parse(manifest),
);

export const getRuntimeManifest = (
  runtime: RuntimeAdapterManifest["runtime"],
): RuntimeAdapterManifest => {
  const manifest = RUNTIME_MANIFESTS.find((candidate) => candidate.runtime === runtime);
  if (!manifest) {
    throw new Error(`Runtime manifest is missing for ${runtime}`);
  }

  return manifest;
};
