export type NodeTheme = "emerald" | "violet" | "amber" | "sky" | "orange" | "teal" | "indigo";

export const themeMap = {
  emerald: {
    ring: "ring-emerald-500/20",
    ringSelected: "ring-emerald-500",
    headerBg: "bg-surface",
    iconBg: "bg-emerald-500/12",
    iconColor: "text-emerald-600 dark:text-emerald-400",
    handleColor: "before:!bg-emerald-500",
  },
  violet: {
    ring: "ring-violet-500/20",
    ringSelected: "ring-violet-500",
    headerBg: "bg-surface",
    iconBg: "bg-violet-500/12",
    iconColor: "text-violet-600 dark:text-violet-400",
    handleColor: "before:!bg-violet-500",
  },
  amber: {
    ring: "ring-amber-500/20",
    ringSelected: "ring-amber-500",
    headerBg: "bg-surface",
    iconBg: "bg-amber-500/12",
    iconColor: "text-amber-600 dark:text-amber-400",
    handleColor: "before:!bg-amber-500",
  },
  sky: {
    ring: "ring-sky-500/20",
    ringSelected: "ring-sky-500",
    headerBg: "bg-surface",
    iconBg: "bg-sky-500/12",
    iconColor: "text-sky-600 dark:text-sky-400",
    handleColor: "before:!bg-sky-500",
  },
  orange: {
    ring: "ring-orange-500/20",
    ringSelected: "ring-orange-500",
    headerBg: "bg-surface",
    iconBg: "bg-orange-500/12",
    iconColor: "text-orange-600 dark:text-orange-400",
    handleColor: "before:!bg-orange-500",
  },
  teal: {
    ring: "ring-teal-500/20",
    ringSelected: "ring-teal-500",
    headerBg: "bg-surface",
    iconBg: "bg-teal-500/12",
    iconColor: "text-teal-600 dark:text-teal-400",
    handleColor: "before:!bg-teal-500",
  },
  indigo: {
    ring: "ring-indigo-500/20",
    ringSelected: "ring-indigo-500",
    headerBg: "bg-surface",
    iconBg: "bg-indigo-500/12",
    iconColor: "text-indigo-600 dark:text-indigo-400",
    handleColor: "before:!bg-indigo-500",
  },
} satisfies Record<NodeTheme, object>;
