/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as BestPracticesRouteImport } from './routes/best-practices'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as OperationsOperationIdRouteImport } from './routes/operations.$operationId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as ProjectsProjectIdWorkspaceRouteImport } from './routes/projects.$projectId.workspace'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const BestPracticesRoute = BestPracticesRouteImport.update({
  id: '/best-practices',
  path: '/best-practices',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const OperationsOperationIdRoute = OperationsOperationIdRouteImport.update({
  id: '/$operationId',
  path: '/$operationId',
  getParentRoute: () => OperationsRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const ProjectsProjectIdWorkspaceRoute =
  ProjectsProjectIdWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/best-practices': typeof BestPracticesRoute
  '/canvas': typeof CanvasRoute
  '/jobs': typeof JobsRouteWithChildren
  '/operations': typeof OperationsRouteWithChildren
  '/pipelines': typeof PipelinesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/operations/$operationId': typeof OperationsOperationIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/workspace': typeof ProjectsProjectIdWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/best-practices': typeof BestPracticesRoute
  '/canvas': typeof CanvasRoute
  '/jobs': typeof JobsRouteWithChildren
  '/operations': typeof OperationsRouteWithChildren
  '/pipelines': typeof PipelinesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/operations/$operationId': typeof OperationsOperationIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/workspace': typeof ProjectsProjectIdWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/best-practices': typeof BestPracticesRoute
  '/canvas': typeof CanvasRoute
  '/jobs': typeof JobsRouteWithChildren
  '/operations': typeof OperationsRouteWithChildren
  '/pipelines': typeof PipelinesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/operations/$operationId': typeof OperationsOperationIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/workspace': typeof ProjectsProjectIdWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/best-practices'
    | '/canvas'
    | '/jobs'
    | '/operations'
    | '/pipelines'
    | '/projects'
    | '/rules'
    | '/settings'
    | '/skills'
    | '/jobs/$jobId'
    | '/operations/$operationId'
    | '/projects/$projectId'
    | '/projects/$projectId/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/best-practices'
    | '/canvas'
    | '/jobs'
    | '/operations'
    | '/pipelines'
    | '/projects'
    | '/rules'
    | '/settings'
    | '/skills'
    | '/jobs/$jobId'
    | '/operations/$operationId'
    | '/projects/$projectId'
    | '/projects/$projectId/workspace'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/best-practices'
    | '/canvas'
    | '/jobs'
    | '/operations'
    | '/pipelines'
    | '/projects'
    | '/rules'
    | '/settings'
    | '/skills'
    | '/jobs/$jobId'
    | '/operations/$operationId'
    | '/projects/$projectId'
    | '/projects/$projectId/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  BestPracticesRoute: typeof BestPracticesRoute
  CanvasRoute: typeof CanvasRoute
  JobsRoute: typeof JobsRouteWithChildren
  OperationsRoute: typeof OperationsRouteWithChildren
  PipelinesRoute: typeof PipelinesRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-practices': {
      id: '/best-practices'
      path: '/best-practices'
      fullPath: '/best-practices'
      preLoaderRoute: typeof BestPracticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/operations/$operationId': {
      id: '/operations/$operationId'
      path: '/$operationId'
      fullPath: '/operations/$operationId'
      preLoaderRoute: typeof OperationsOperationIdRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/projects/$projectId/workspace': {
      id: '/projects/$projectId/workspace'
      path: '/workspace'
      fullPath: '/projects/$projectId/workspace'
      preLoaderRoute: typeof ProjectsProjectIdWorkspaceRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface OperationsRouteChildren {
  OperationsOperationIdRoute: typeof OperationsOperationIdRoute
}

const OperationsRouteChildren: OperationsRouteChildren = {
  OperationsOperationIdRoute: OperationsOperationIdRoute,
}

const OperationsRouteWithChildren = OperationsRoute._addFileChildren(
  OperationsRouteChildren,
)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdWorkspaceRoute: typeof ProjectsProjectIdWorkspaceRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdWorkspaceRoute: ProjectsProjectIdWorkspaceRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  BestPracticesRoute: BestPracticesRoute,
  CanvasRoute: CanvasRoute,
  JobsRoute: JobsRouteWithChildren,
  OperationsRoute: OperationsRouteWithChildren,
  PipelinesRoute: PipelinesRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
