/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRuntimesRouteImport } from './routes/_layout/runtimes'
import { Route as LayoutPluginsRouteImport } from './routes/_layout/plugins'
import { Route as LayoutPipelinesRouteImport } from './routes/_layout/pipelines'
import { Route as LayoutDistillationsRouteImport } from './routes/_layout/distillations'
import { Route as LayoutDistillationStudioRouteImport } from './routes/_layout/distillation-studio'
import { Route as LayoutAssistantRouteImport } from './routes/_layout/assistant'
import { Route as LayoutRuntimesIndexRouteImport } from './routes/_layout/runtimes.index'
import { Route as LayoutProjectsIndexRouteImport } from './routes/_layout/projects.index'
import { Route as LayoutPipelinesIndexRouteImport } from './routes/_layout/pipelines.index'
import { Route as LayoutDistillationsIndexRouteImport } from './routes/_layout/distillations.index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as LayoutPipelinesSkillsRouteImport } from './routes/_layout/pipelines.skills'
import { Route as LayoutPipelinesRecipesRouteImport } from './routes/_layout/pipelines.recipes'
import { Route as LayoutPipelinesObjectsRouteImport } from './routes/_layout/pipelines.objects'
import { Route as LayoutPipelinesJobsRouteImport } from './routes/_layout/pipelines.jobs'
import { Route as LayoutPipelinesPipelineIdRouteImport } from './routes/_layout/pipelines.$pipelineId'
import { Route as LayoutDistillationsNewRouteImport } from './routes/_layout/distillations.new'
import { Route as LayoutDistillationsDistillationIdRouteImport } from './routes/_layout/distillations.$distillationId'
import { Route as LayoutRuntimesRuntimeIdIndexRouteImport } from './routes/_layout/runtimes.$runtimeId.index'
import { Route as LayoutProjectsProjectIdIndexRouteImport } from './routes/_layout/projects.$projectId.index'
import { Route as LayoutPipelinesRulesIndexRouteImport } from './routes/_layout/pipelines.rules.index'
import { Route as LayoutPipelinesOperationsIndexRouteImport } from './routes/_layout/pipelines.operations.index'
import { Route as LayoutPipelinesJobsIndexRouteImport } from './routes/_layout/pipelines.jobs.index'
import { Route as LayoutPipelinesBestPracticesIndexRouteImport } from './routes/_layout/pipelines.best-practices.index'
import { Route as LayoutRuntimesRuntimeIdEditRouteImport } from './routes/_layout/runtimes.$runtimeId.edit'
import { Route as LayoutProjectsProjectIdWorkspaceRouteImport } from './routes/_layout/projects.$projectId.workspace'
import { Route as LayoutPipelinesRulesCreateRouteImport } from './routes/_layout/pipelines.rules.create'
import { Route as LayoutPipelinesOperationsNewRouteImport } from './routes/_layout/pipelines.operations.new'
import { Route as LayoutPipelinesJobsJobIdRouteImport } from './routes/_layout/pipelines.jobs.$jobId'
import { Route as LayoutPipelinesRulesRuleIdIndexRouteImport } from './routes/_layout/pipelines.rules.$ruleId.index'
import { Route as LayoutPipelinesOperationsOperationIdIndexRouteImport } from './routes/_layout/pipelines.operations.$operationId.index'
import { Route as LayoutPipelinesBestPracticesBestPracticeIdIndexRouteImport } from './routes/_layout/pipelines.best-practices.$bestPracticeId.index'
import { Route as LayoutPipelinesRulesRuleIdEditRouteImport } from './routes/_layout/pipelines.rules.$ruleId.edit'
import { Route as LayoutPipelinesOperationsOperationIdEditRouteImport } from './routes/_layout/pipelines.operations.$operationId.edit'
import { Route as LayoutPipelinesBestPracticesBestPracticeIdEditRouteImport } from './routes/_layout/pipelines.best-practices.$bestPracticeId.edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRuntimesRoute = LayoutRuntimesRouteImport.update({
  id: '/runtimes',
  path: '/runtimes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPluginsRoute = LayoutPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPipelinesRoute = LayoutPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDistillationsRoute = LayoutDistillationsRouteImport.update({
  id: '/distillations',
  path: '/distillations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDistillationStudioRoute =
  LayoutDistillationStudioRouteImport.update({
    id: '/distillation-studio',
    path: '/distillation-studio',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAssistantRoute = LayoutAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRuntimesIndexRoute = LayoutRuntimesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRuntimesRoute,
} as any)
const LayoutProjectsIndexRoute = LayoutProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPipelinesIndexRoute = LayoutPipelinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPipelinesRoute,
} as any)
const LayoutDistillationsIndexRoute =
  LayoutDistillationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutDistillationsRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPipelinesSkillsRoute = LayoutPipelinesSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => LayoutPipelinesRoute,
} as any)
const LayoutPipelinesRecipesRoute = LayoutPipelinesRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => LayoutPipelinesRoute,
} as any)
const LayoutPipelinesObjectsRoute = LayoutPipelinesObjectsRouteImport.update({
  id: '/objects',
  path: '/objects',
  getParentRoute: () => LayoutPipelinesRoute,
} as any)
const LayoutPipelinesJobsRoute = LayoutPipelinesJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => LayoutPipelinesRoute,
} as any)
const LayoutPipelinesPipelineIdRoute =
  LayoutPipelinesPipelineIdRouteImport.update({
    id: '/$pipelineId',
    path: '/$pipelineId',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)
const LayoutDistillationsNewRoute = LayoutDistillationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutDistillationsRoute,
} as any)
const LayoutDistillationsDistillationIdRoute =
  LayoutDistillationsDistillationIdRouteImport.update({
    id: '/$distillationId',
    path: '/$distillationId',
    getParentRoute: () => LayoutDistillationsRoute,
  } as any)
const LayoutRuntimesRuntimeIdIndexRoute =
  LayoutRuntimesRuntimeIdIndexRouteImport.update({
    id: '/$runtimeId/',
    path: '/$runtimeId/',
    getParentRoute: () => LayoutRuntimesRoute,
  } as any)
const LayoutProjectsProjectIdIndexRoute =
  LayoutProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPipelinesRulesIndexRoute =
  LayoutPipelinesRulesIndexRouteImport.update({
    id: '/rules/',
    path: '/rules/',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)
const LayoutPipelinesOperationsIndexRoute =
  LayoutPipelinesOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)
const LayoutPipelinesJobsIndexRoute =
  LayoutPipelinesJobsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutPipelinesJobsRoute,
  } as any)
const LayoutPipelinesBestPracticesIndexRoute =
  LayoutPipelinesBestPracticesIndexRouteImport.update({
    id: '/best-practices/',
    path: '/best-practices/',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)
const LayoutRuntimesRuntimeIdEditRoute =
  LayoutRuntimesRuntimeIdEditRouteImport.update({
    id: '/$runtimeId/edit',
    path: '/$runtimeId/edit',
    getParentRoute: () => LayoutRuntimesRoute,
  } as any)
const LayoutProjectsProjectIdWorkspaceRoute =
  LayoutProjectsProjectIdWorkspaceRouteImport.update({
    id: '/projects/$projectId/workspace',
    path: '/projects/$projectId/workspace',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPipelinesRulesCreateRoute =
  LayoutPipelinesRulesCreateRouteImport.update({
    id: '/rules/create',
    path: '/rules/create',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)
const LayoutPipelinesOperationsNewRoute =
  LayoutPipelinesOperationsNewRouteImport.update({
    id: '/operations/new',
    path: '/operations/new',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)
const LayoutPipelinesJobsJobIdRoute =
  LayoutPipelinesJobsJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => LayoutPipelinesJobsRoute,
  } as any)
const LayoutPipelinesRulesRuleIdIndexRoute =
  LayoutPipelinesRulesRuleIdIndexRouteImport.update({
    id: '/rules/$ruleId/',
    path: '/rules/$ruleId/',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)
const LayoutPipelinesOperationsOperationIdIndexRoute =
  LayoutPipelinesOperationsOperationIdIndexRouteImport.update({
    id: '/operations/$operationId/',
    path: '/operations/$operationId/',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)
const LayoutPipelinesBestPracticesBestPracticeIdIndexRoute =
  LayoutPipelinesBestPracticesBestPracticeIdIndexRouteImport.update({
    id: '/best-practices/$bestPracticeId/',
    path: '/best-practices/$bestPracticeId/',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)
const LayoutPipelinesRulesRuleIdEditRoute =
  LayoutPipelinesRulesRuleIdEditRouteImport.update({
    id: '/rules/$ruleId/edit',
    path: '/rules/$ruleId/edit',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)
const LayoutPipelinesOperationsOperationIdEditRoute =
  LayoutPipelinesOperationsOperationIdEditRouteImport.update({
    id: '/operations/$operationId/edit',
    path: '/operations/$operationId/edit',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)
const LayoutPipelinesBestPracticesBestPracticeIdEditRoute =
  LayoutPipelinesBestPracticesBestPracticeIdEditRouteImport.update({
    id: '/best-practices/$bestPracticeId/edit',
    path: '/best-practices/$bestPracticeId/edit',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/canvas': typeof CanvasRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/assistant': typeof LayoutAssistantRoute
  '/distillation-studio': typeof LayoutDistillationStudioRoute
  '/distillations': typeof LayoutDistillationsRouteWithChildren
  '/pipelines': typeof LayoutPipelinesRouteWithChildren
  '/plugins': typeof LayoutPluginsRoute
  '/runtimes': typeof LayoutRuntimesRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/distillations/$distillationId': typeof LayoutDistillationsDistillationIdRoute
  '/distillations/new': typeof LayoutDistillationsNewRoute
  '/pipelines/$pipelineId': typeof LayoutPipelinesPipelineIdRoute
  '/pipelines/jobs': typeof LayoutPipelinesJobsRouteWithChildren
  '/pipelines/objects': typeof LayoutPipelinesObjectsRoute
  '/pipelines/recipes': typeof LayoutPipelinesRecipesRoute
  '/pipelines/skills': typeof LayoutPipelinesSkillsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/distillations/': typeof LayoutDistillationsIndexRoute
  '/pipelines/': typeof LayoutPipelinesIndexRoute
  '/projects/': typeof LayoutProjectsIndexRoute
  '/runtimes/': typeof LayoutRuntimesIndexRoute
  '/pipelines/jobs/$jobId': typeof LayoutPipelinesJobsJobIdRoute
  '/pipelines/operations/new': typeof LayoutPipelinesOperationsNewRoute
  '/pipelines/rules/create': typeof LayoutPipelinesRulesCreateRoute
  '/projects/$projectId/workspace': typeof LayoutProjectsProjectIdWorkspaceRoute
  '/runtimes/$runtimeId/edit': typeof LayoutRuntimesRuntimeIdEditRoute
  '/pipelines/best-practices/': typeof LayoutPipelinesBestPracticesIndexRoute
  '/pipelines/jobs/': typeof LayoutPipelinesJobsIndexRoute
  '/pipelines/operations/': typeof LayoutPipelinesOperationsIndexRoute
  '/pipelines/rules/': typeof LayoutPipelinesRulesIndexRoute
  '/projects/$projectId/': typeof LayoutProjectsProjectIdIndexRoute
  '/runtimes/$runtimeId/': typeof LayoutRuntimesRuntimeIdIndexRoute
  '/pipelines/best-practices/$bestPracticeId/edit': typeof LayoutPipelinesBestPracticesBestPracticeIdEditRoute
  '/pipelines/operations/$operationId/edit': typeof LayoutPipelinesOperationsOperationIdEditRoute
  '/pipelines/rules/$ruleId/edit': typeof LayoutPipelinesRulesRuleIdEditRoute
  '/pipelines/best-practices/$bestPracticeId/': typeof LayoutPipelinesBestPracticesBestPracticeIdIndexRoute
  '/pipelines/operations/$operationId/': typeof LayoutPipelinesOperationsOperationIdIndexRoute
  '/pipelines/rules/$ruleId/': typeof LayoutPipelinesRulesRuleIdIndexRoute
}
export interface FileRoutesByTo {
  '/canvas': typeof CanvasRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/assistant': typeof LayoutAssistantRoute
  '/distillation-studio': typeof LayoutDistillationStudioRoute
  '/plugins': typeof LayoutPluginsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/distillations/$distillationId': typeof LayoutDistillationsDistillationIdRoute
  '/distillations/new': typeof LayoutDistillationsNewRoute
  '/pipelines/$pipelineId': typeof LayoutPipelinesPipelineIdRoute
  '/pipelines/objects': typeof LayoutPipelinesObjectsRoute
  '/pipelines/recipes': typeof LayoutPipelinesRecipesRoute
  '/pipelines/skills': typeof LayoutPipelinesSkillsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/distillations': typeof LayoutDistillationsIndexRoute
  '/pipelines': typeof LayoutPipelinesIndexRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/runtimes': typeof LayoutRuntimesIndexRoute
  '/pipelines/jobs/$jobId': typeof LayoutPipelinesJobsJobIdRoute
  '/pipelines/operations/new': typeof LayoutPipelinesOperationsNewRoute
  '/pipelines/rules/create': typeof LayoutPipelinesRulesCreateRoute
  '/projects/$projectId/workspace': typeof LayoutProjectsProjectIdWorkspaceRoute
  '/runtimes/$runtimeId/edit': typeof LayoutRuntimesRuntimeIdEditRoute
  '/pipelines/best-practices': typeof LayoutPipelinesBestPracticesIndexRoute
  '/pipelines/jobs': typeof LayoutPipelinesJobsIndexRoute
  '/pipelines/operations': typeof LayoutPipelinesOperationsIndexRoute
  '/pipelines/rules': typeof LayoutPipelinesRulesIndexRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdIndexRoute
  '/runtimes/$runtimeId': typeof LayoutRuntimesRuntimeIdIndexRoute
  '/pipelines/best-practices/$bestPracticeId/edit': typeof LayoutPipelinesBestPracticesBestPracticeIdEditRoute
  '/pipelines/operations/$operationId/edit': typeof LayoutPipelinesOperationsOperationIdEditRoute
  '/pipelines/rules/$ruleId/edit': typeof LayoutPipelinesRulesRuleIdEditRoute
  '/pipelines/best-practices/$bestPracticeId': typeof LayoutPipelinesBestPracticesBestPracticeIdIndexRoute
  '/pipelines/operations/$operationId': typeof LayoutPipelinesOperationsOperationIdIndexRoute
  '/pipelines/rules/$ruleId': typeof LayoutPipelinesRulesRuleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/canvas': typeof CanvasRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/_layout/assistant': typeof LayoutAssistantRoute
  '/_layout/distillation-studio': typeof LayoutDistillationStudioRoute
  '/_layout/distillations': typeof LayoutDistillationsRouteWithChildren
  '/_layout/pipelines': typeof LayoutPipelinesRouteWithChildren
  '/_layout/plugins': typeof LayoutPluginsRoute
  '/_layout/runtimes': typeof LayoutRuntimesRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/distillations/$distillationId': typeof LayoutDistillationsDistillationIdRoute
  '/_layout/distillations/new': typeof LayoutDistillationsNewRoute
  '/_layout/pipelines/$pipelineId': typeof LayoutPipelinesPipelineIdRoute
  '/_layout/pipelines/jobs': typeof LayoutPipelinesJobsRouteWithChildren
  '/_layout/pipelines/objects': typeof LayoutPipelinesObjectsRoute
  '/_layout/pipelines/recipes': typeof LayoutPipelinesRecipesRoute
  '/_layout/pipelines/skills': typeof LayoutPipelinesSkillsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_layout/distillations/': typeof LayoutDistillationsIndexRoute
  '/_layout/pipelines/': typeof LayoutPipelinesIndexRoute
  '/_layout/projects/': typeof LayoutProjectsIndexRoute
  '/_layout/runtimes/': typeof LayoutRuntimesIndexRoute
  '/_layout/pipelines/jobs/$jobId': typeof LayoutPipelinesJobsJobIdRoute
  '/_layout/pipelines/operations/new': typeof LayoutPipelinesOperationsNewRoute
  '/_layout/pipelines/rules/create': typeof LayoutPipelinesRulesCreateRoute
  '/_layout/projects/$projectId/workspace': typeof LayoutProjectsProjectIdWorkspaceRoute
  '/_layout/runtimes/$runtimeId/edit': typeof LayoutRuntimesRuntimeIdEditRoute
  '/_layout/pipelines/best-practices/': typeof LayoutPipelinesBestPracticesIndexRoute
  '/_layout/pipelines/jobs/': typeof LayoutPipelinesJobsIndexRoute
  '/_layout/pipelines/operations/': typeof LayoutPipelinesOperationsIndexRoute
  '/_layout/pipelines/rules/': typeof LayoutPipelinesRulesIndexRoute
  '/_layout/projects/$projectId/': typeof LayoutProjectsProjectIdIndexRoute
  '/_layout/runtimes/$runtimeId/': typeof LayoutRuntimesRuntimeIdIndexRoute
  '/_layout/pipelines/best-practices/$bestPracticeId/edit': typeof LayoutPipelinesBestPracticesBestPracticeIdEditRoute
  '/_layout/pipelines/operations/$operationId/edit': typeof LayoutPipelinesOperationsOperationIdEditRoute
  '/_layout/pipelines/rules/$ruleId/edit': typeof LayoutPipelinesRulesRuleIdEditRoute
  '/_layout/pipelines/best-practices/$bestPracticeId/': typeof LayoutPipelinesBestPracticesBestPracticeIdIndexRoute
  '/_layout/pipelines/operations/$operationId/': typeof LayoutPipelinesOperationsOperationIdIndexRoute
  '/_layout/pipelines/rules/$ruleId/': typeof LayoutPipelinesRulesRuleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canvas'
    | '/login'
    | '/sign-up'
    | '/assistant'
    | '/distillation-studio'
    | '/distillations'
    | '/pipelines'
    | '/plugins'
    | '/runtimes'
    | '/settings'
    | '/distillations/$distillationId'
    | '/distillations/new'
    | '/pipelines/$pipelineId'
    | '/pipelines/jobs'
    | '/pipelines/objects'
    | '/pipelines/recipes'
    | '/pipelines/skills'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/distillations/'
    | '/pipelines/'
    | '/projects/'
    | '/runtimes/'
    | '/pipelines/jobs/$jobId'
    | '/pipelines/operations/new'
    | '/pipelines/rules/create'
    | '/projects/$projectId/workspace'
    | '/runtimes/$runtimeId/edit'
    | '/pipelines/best-practices/'
    | '/pipelines/jobs/'
    | '/pipelines/operations/'
    | '/pipelines/rules/'
    | '/projects/$projectId/'
    | '/runtimes/$runtimeId/'
    | '/pipelines/best-practices/$bestPracticeId/edit'
    | '/pipelines/operations/$operationId/edit'
    | '/pipelines/rules/$ruleId/edit'
    | '/pipelines/best-practices/$bestPracticeId/'
    | '/pipelines/operations/$operationId/'
    | '/pipelines/rules/$ruleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/canvas'
    | '/login'
    | '/sign-up'
    | '/assistant'
    | '/distillation-studio'
    | '/plugins'
    | '/settings'
    | '/'
    | '/distillations/$distillationId'
    | '/distillations/new'
    | '/pipelines/$pipelineId'
    | '/pipelines/objects'
    | '/pipelines/recipes'
    | '/pipelines/skills'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/distillations'
    | '/pipelines'
    | '/projects'
    | '/runtimes'
    | '/pipelines/jobs/$jobId'
    | '/pipelines/operations/new'
    | '/pipelines/rules/create'
    | '/projects/$projectId/workspace'
    | '/runtimes/$runtimeId/edit'
    | '/pipelines/best-practices'
    | '/pipelines/jobs'
    | '/pipelines/operations'
    | '/pipelines/rules'
    | '/projects/$projectId'
    | '/runtimes/$runtimeId'
    | '/pipelines/best-practices/$bestPracticeId/edit'
    | '/pipelines/operations/$operationId/edit'
    | '/pipelines/rules/$ruleId/edit'
    | '/pipelines/best-practices/$bestPracticeId'
    | '/pipelines/operations/$operationId'
    | '/pipelines/rules/$ruleId'
  id:
    | '__root__'
    | '/_layout'
    | '/canvas'
    | '/login'
    | '/sign-up'
    | '/_layout/assistant'
    | '/_layout/distillation-studio'
    | '/_layout/distillations'
    | '/_layout/pipelines'
    | '/_layout/plugins'
    | '/_layout/runtimes'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/distillations/$distillationId'
    | '/_layout/distillations/new'
    | '/_layout/pipelines/$pipelineId'
    | '/_layout/pipelines/jobs'
    | '/_layout/pipelines/objects'
    | '/_layout/pipelines/recipes'
    | '/_layout/pipelines/skills'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_layout/distillations/'
    | '/_layout/pipelines/'
    | '/_layout/projects/'
    | '/_layout/runtimes/'
    | '/_layout/pipelines/jobs/$jobId'
    | '/_layout/pipelines/operations/new'
    | '/_layout/pipelines/rules/create'
    | '/_layout/projects/$projectId/workspace'
    | '/_layout/runtimes/$runtimeId/edit'
    | '/_layout/pipelines/best-practices/'
    | '/_layout/pipelines/jobs/'
    | '/_layout/pipelines/operations/'
    | '/_layout/pipelines/rules/'
    | '/_layout/projects/$projectId/'
    | '/_layout/runtimes/$runtimeId/'
    | '/_layout/pipelines/best-practices/$bestPracticeId/edit'
    | '/_layout/pipelines/operations/$operationId/edit'
    | '/_layout/pipelines/rules/$ruleId/edit'
    | '/_layout/pipelines/best-practices/$bestPracticeId/'
    | '/_layout/pipelines/operations/$operationId/'
    | '/_layout/pipelines/rules/$ruleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  CanvasRoute: typeof CanvasRoute
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/runtimes': {
      id: '/_layout/runtimes'
      path: '/runtimes'
      fullPath: '/runtimes'
      preLoaderRoute: typeof LayoutRuntimesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/plugins': {
      id: '/_layout/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof LayoutPluginsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pipelines': {
      id: '/_layout/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof LayoutPipelinesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/distillations': {
      id: '/_layout/distillations'
      path: '/distillations'
      fullPath: '/distillations'
      preLoaderRoute: typeof LayoutDistillationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/distillation-studio': {
      id: '/_layout/distillation-studio'
      path: '/distillation-studio'
      fullPath: '/distillation-studio'
      preLoaderRoute: typeof LayoutDistillationStudioRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/assistant': {
      id: '/_layout/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof LayoutAssistantRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/runtimes/': {
      id: '/_layout/runtimes/'
      path: '/'
      fullPath: '/runtimes/'
      preLoaderRoute: typeof LayoutRuntimesIndexRouteImport
      parentRoute: typeof LayoutRuntimesRoute
    }
    '/_layout/projects/': {
      id: '/_layout/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof LayoutProjectsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pipelines/': {
      id: '/_layout/pipelines/'
      path: '/'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof LayoutPipelinesIndexRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/distillations/': {
      id: '/_layout/distillations/'
      path: '/'
      fullPath: '/distillations/'
      preLoaderRoute: typeof LayoutDistillationsIndexRouteImport
      parentRoute: typeof LayoutDistillationsRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/pipelines/skills': {
      id: '/_layout/pipelines/skills'
      path: '/skills'
      fullPath: '/pipelines/skills'
      preLoaderRoute: typeof LayoutPipelinesSkillsRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/recipes': {
      id: '/_layout/pipelines/recipes'
      path: '/recipes'
      fullPath: '/pipelines/recipes'
      preLoaderRoute: typeof LayoutPipelinesRecipesRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/objects': {
      id: '/_layout/pipelines/objects'
      path: '/objects'
      fullPath: '/pipelines/objects'
      preLoaderRoute: typeof LayoutPipelinesObjectsRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/jobs': {
      id: '/_layout/pipelines/jobs'
      path: '/jobs'
      fullPath: '/pipelines/jobs'
      preLoaderRoute: typeof LayoutPipelinesJobsRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/$pipelineId': {
      id: '/_layout/pipelines/$pipelineId'
      path: '/$pipelineId'
      fullPath: '/pipelines/$pipelineId'
      preLoaderRoute: typeof LayoutPipelinesPipelineIdRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/distillations/new': {
      id: '/_layout/distillations/new'
      path: '/new'
      fullPath: '/distillations/new'
      preLoaderRoute: typeof LayoutDistillationsNewRouteImport
      parentRoute: typeof LayoutDistillationsRoute
    }
    '/_layout/distillations/$distillationId': {
      id: '/_layout/distillations/$distillationId'
      path: '/$distillationId'
      fullPath: '/distillations/$distillationId'
      preLoaderRoute: typeof LayoutDistillationsDistillationIdRouteImport
      parentRoute: typeof LayoutDistillationsRoute
    }
    '/_layout/runtimes/$runtimeId/': {
      id: '/_layout/runtimes/$runtimeId/'
      path: '/$runtimeId'
      fullPath: '/runtimes/$runtimeId/'
      preLoaderRoute: typeof LayoutRuntimesRuntimeIdIndexRouteImport
      parentRoute: typeof LayoutRuntimesRoute
    }
    '/_layout/projects/$projectId/': {
      id: '/_layout/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof LayoutProjectsProjectIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pipelines/rules/': {
      id: '/_layout/pipelines/rules/'
      path: '/rules'
      fullPath: '/pipelines/rules/'
      preLoaderRoute: typeof LayoutPipelinesRulesIndexRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/operations/': {
      id: '/_layout/pipelines/operations/'
      path: '/operations'
      fullPath: '/pipelines/operations/'
      preLoaderRoute: typeof LayoutPipelinesOperationsIndexRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/jobs/': {
      id: '/_layout/pipelines/jobs/'
      path: '/'
      fullPath: '/pipelines/jobs/'
      preLoaderRoute: typeof LayoutPipelinesJobsIndexRouteImport
      parentRoute: typeof LayoutPipelinesJobsRoute
    }
    '/_layout/pipelines/best-practices/': {
      id: '/_layout/pipelines/best-practices/'
      path: '/best-practices'
      fullPath: '/pipelines/best-practices/'
      preLoaderRoute: typeof LayoutPipelinesBestPracticesIndexRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/runtimes/$runtimeId/edit': {
      id: '/_layout/runtimes/$runtimeId/edit'
      path: '/$runtimeId/edit'
      fullPath: '/runtimes/$runtimeId/edit'
      preLoaderRoute: typeof LayoutRuntimesRuntimeIdEditRouteImport
      parentRoute: typeof LayoutRuntimesRoute
    }
    '/_layout/projects/$projectId/workspace': {
      id: '/_layout/projects/$projectId/workspace'
      path: '/projects/$projectId/workspace'
      fullPath: '/projects/$projectId/workspace'
      preLoaderRoute: typeof LayoutProjectsProjectIdWorkspaceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pipelines/rules/create': {
      id: '/_layout/pipelines/rules/create'
      path: '/rules/create'
      fullPath: '/pipelines/rules/create'
      preLoaderRoute: typeof LayoutPipelinesRulesCreateRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/operations/new': {
      id: '/_layout/pipelines/operations/new'
      path: '/operations/new'
      fullPath: '/pipelines/operations/new'
      preLoaderRoute: typeof LayoutPipelinesOperationsNewRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/jobs/$jobId': {
      id: '/_layout/pipelines/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/pipelines/jobs/$jobId'
      preLoaderRoute: typeof LayoutPipelinesJobsJobIdRouteImport
      parentRoute: typeof LayoutPipelinesJobsRoute
    }
    '/_layout/pipelines/rules/$ruleId/': {
      id: '/_layout/pipelines/rules/$ruleId/'
      path: '/rules/$ruleId'
      fullPath: '/pipelines/rules/$ruleId/'
      preLoaderRoute: typeof LayoutPipelinesRulesRuleIdIndexRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/operations/$operationId/': {
      id: '/_layout/pipelines/operations/$operationId/'
      path: '/operations/$operationId'
      fullPath: '/pipelines/operations/$operationId/'
      preLoaderRoute: typeof LayoutPipelinesOperationsOperationIdIndexRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/best-practices/$bestPracticeId/': {
      id: '/_layout/pipelines/best-practices/$bestPracticeId/'
      path: '/best-practices/$bestPracticeId'
      fullPath: '/pipelines/best-practices/$bestPracticeId/'
      preLoaderRoute: typeof LayoutPipelinesBestPracticesBestPracticeIdIndexRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/rules/$ruleId/edit': {
      id: '/_layout/pipelines/rules/$ruleId/edit'
      path: '/rules/$ruleId/edit'
      fullPath: '/pipelines/rules/$ruleId/edit'
      preLoaderRoute: typeof LayoutPipelinesRulesRuleIdEditRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/operations/$operationId/edit': {
      id: '/_layout/pipelines/operations/$operationId/edit'
      path: '/operations/$operationId/edit'
      fullPath: '/pipelines/operations/$operationId/edit'
      preLoaderRoute: typeof LayoutPipelinesOperationsOperationIdEditRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/best-practices/$bestPracticeId/edit': {
      id: '/_layout/pipelines/best-practices/$bestPracticeId/edit'
      path: '/best-practices/$bestPracticeId/edit'
      fullPath: '/pipelines/best-practices/$bestPracticeId/edit'
      preLoaderRoute: typeof LayoutPipelinesBestPracticesBestPracticeIdEditRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
  }
}

interface LayoutDistillationsRouteChildren {
  LayoutDistillationsDistillationIdRoute: typeof LayoutDistillationsDistillationIdRoute
  LayoutDistillationsNewRoute: typeof LayoutDistillationsNewRoute
  LayoutDistillationsIndexRoute: typeof LayoutDistillationsIndexRoute
}

const LayoutDistillationsRouteChildren: LayoutDistillationsRouteChildren = {
  LayoutDistillationsDistillationIdRoute:
    LayoutDistillationsDistillationIdRoute,
  LayoutDistillationsNewRoute: LayoutDistillationsNewRoute,
  LayoutDistillationsIndexRoute: LayoutDistillationsIndexRoute,
}

const LayoutDistillationsRouteWithChildren =
  LayoutDistillationsRoute._addFileChildren(LayoutDistillationsRouteChildren)

interface LayoutPipelinesJobsRouteChildren {
  LayoutPipelinesJobsJobIdRoute: typeof LayoutPipelinesJobsJobIdRoute
  LayoutPipelinesJobsIndexRoute: typeof LayoutPipelinesJobsIndexRoute
}

const LayoutPipelinesJobsRouteChildren: LayoutPipelinesJobsRouteChildren = {
  LayoutPipelinesJobsJobIdRoute: LayoutPipelinesJobsJobIdRoute,
  LayoutPipelinesJobsIndexRoute: LayoutPipelinesJobsIndexRoute,
}

const LayoutPipelinesJobsRouteWithChildren =
  LayoutPipelinesJobsRoute._addFileChildren(LayoutPipelinesJobsRouteChildren)

interface LayoutPipelinesRouteChildren {
  LayoutPipelinesPipelineIdRoute: typeof LayoutPipelinesPipelineIdRoute
  LayoutPipelinesJobsRoute: typeof LayoutPipelinesJobsRouteWithChildren
  LayoutPipelinesObjectsRoute: typeof LayoutPipelinesObjectsRoute
  LayoutPipelinesRecipesRoute: typeof LayoutPipelinesRecipesRoute
  LayoutPipelinesSkillsRoute: typeof LayoutPipelinesSkillsRoute
  LayoutPipelinesIndexRoute: typeof LayoutPipelinesIndexRoute
  LayoutPipelinesOperationsNewRoute: typeof LayoutPipelinesOperationsNewRoute
  LayoutPipelinesRulesCreateRoute: typeof LayoutPipelinesRulesCreateRoute
  LayoutPipelinesBestPracticesIndexRoute: typeof LayoutPipelinesBestPracticesIndexRoute
  LayoutPipelinesOperationsIndexRoute: typeof LayoutPipelinesOperationsIndexRoute
  LayoutPipelinesRulesIndexRoute: typeof LayoutPipelinesRulesIndexRoute
  LayoutPipelinesBestPracticesBestPracticeIdEditRoute: typeof LayoutPipelinesBestPracticesBestPracticeIdEditRoute
  LayoutPipelinesOperationsOperationIdEditRoute: typeof LayoutPipelinesOperationsOperationIdEditRoute
  LayoutPipelinesRulesRuleIdEditRoute: typeof LayoutPipelinesRulesRuleIdEditRoute
  LayoutPipelinesBestPracticesBestPracticeIdIndexRoute: typeof LayoutPipelinesBestPracticesBestPracticeIdIndexRoute
  LayoutPipelinesOperationsOperationIdIndexRoute: typeof LayoutPipelinesOperationsOperationIdIndexRoute
  LayoutPipelinesRulesRuleIdIndexRoute: typeof LayoutPipelinesRulesRuleIdIndexRoute
}

const LayoutPipelinesRouteChildren: LayoutPipelinesRouteChildren = {
  LayoutPipelinesPipelineIdRoute: LayoutPipelinesPipelineIdRoute,
  LayoutPipelinesJobsRoute: LayoutPipelinesJobsRouteWithChildren,
  LayoutPipelinesObjectsRoute: LayoutPipelinesObjectsRoute,
  LayoutPipelinesRecipesRoute: LayoutPipelinesRecipesRoute,
  LayoutPipelinesSkillsRoute: LayoutPipelinesSkillsRoute,
  LayoutPipelinesIndexRoute: LayoutPipelinesIndexRoute,
  LayoutPipelinesOperationsNewRoute: LayoutPipelinesOperationsNewRoute,
  LayoutPipelinesRulesCreateRoute: LayoutPipelinesRulesCreateRoute,
  LayoutPipelinesBestPracticesIndexRoute:
    LayoutPipelinesBestPracticesIndexRoute,
  LayoutPipelinesOperationsIndexRoute: LayoutPipelinesOperationsIndexRoute,
  LayoutPipelinesRulesIndexRoute: LayoutPipelinesRulesIndexRoute,
  LayoutPipelinesBestPracticesBestPracticeIdEditRoute:
    LayoutPipelinesBestPracticesBestPracticeIdEditRoute,
  LayoutPipelinesOperationsOperationIdEditRoute:
    LayoutPipelinesOperationsOperationIdEditRoute,
  LayoutPipelinesRulesRuleIdEditRoute: LayoutPipelinesRulesRuleIdEditRoute,
  LayoutPipelinesBestPracticesBestPracticeIdIndexRoute:
    LayoutPipelinesBestPracticesBestPracticeIdIndexRoute,
  LayoutPipelinesOperationsOperationIdIndexRoute:
    LayoutPipelinesOperationsOperationIdIndexRoute,
  LayoutPipelinesRulesRuleIdIndexRoute: LayoutPipelinesRulesRuleIdIndexRoute,
}

const LayoutPipelinesRouteWithChildren = LayoutPipelinesRoute._addFileChildren(
  LayoutPipelinesRouteChildren,
)

interface LayoutRuntimesRouteChildren {
  LayoutRuntimesIndexRoute: typeof LayoutRuntimesIndexRoute
  LayoutRuntimesRuntimeIdEditRoute: typeof LayoutRuntimesRuntimeIdEditRoute
  LayoutRuntimesRuntimeIdIndexRoute: typeof LayoutRuntimesRuntimeIdIndexRoute
}

const LayoutRuntimesRouteChildren: LayoutRuntimesRouteChildren = {
  LayoutRuntimesIndexRoute: LayoutRuntimesIndexRoute,
  LayoutRuntimesRuntimeIdEditRoute: LayoutRuntimesRuntimeIdEditRoute,
  LayoutRuntimesRuntimeIdIndexRoute: LayoutRuntimesRuntimeIdIndexRoute,
}

const LayoutRuntimesRouteWithChildren = LayoutRuntimesRoute._addFileChildren(
  LayoutRuntimesRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAssistantRoute: typeof LayoutAssistantRoute
  LayoutDistillationStudioRoute: typeof LayoutDistillationStudioRoute
  LayoutDistillationsRoute: typeof LayoutDistillationsRouteWithChildren
  LayoutPipelinesRoute: typeof LayoutPipelinesRouteWithChildren
  LayoutPluginsRoute: typeof LayoutPluginsRoute
  LayoutRuntimesRoute: typeof LayoutRuntimesRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProjectsIndexRoute: typeof LayoutProjectsIndexRoute
  LayoutProjectsProjectIdWorkspaceRoute: typeof LayoutProjectsProjectIdWorkspaceRoute
  LayoutProjectsProjectIdIndexRoute: typeof LayoutProjectsProjectIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAssistantRoute: LayoutAssistantRoute,
  LayoutDistillationStudioRoute: LayoutDistillationStudioRoute,
  LayoutDistillationsRoute: LayoutDistillationsRouteWithChildren,
  LayoutPipelinesRoute: LayoutPipelinesRouteWithChildren,
  LayoutPluginsRoute: LayoutPluginsRoute,
  LayoutRuntimesRoute: LayoutRuntimesRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProjectsIndexRoute: LayoutProjectsIndexRoute,
  LayoutProjectsProjectIdWorkspaceRoute: LayoutProjectsProjectIdWorkspaceRoute,
  LayoutProjectsProjectIdIndexRoute: LayoutProjectsProjectIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  CanvasRoute: CanvasRoute,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
