/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as ApiLocalSessionRouteImport } from './routes/api/local-session'
import { Route as LayoutUsageRouteImport } from './routes/_layout/usage'
import { Route as LayoutSkillsRouteImport } from './routes/_layout/skills'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPluginsRouteImport } from './routes/_layout/plugins'
import { Route as LayoutPipelinesRouteImport } from './routes/_layout/pipelines'
import { Route as LayoutLocalAgentsRouteImport } from './routes/_layout/local-agents'
import { Route as LayoutConnectorsRouteImport } from './routes/_layout/connectors'
import { Route as LayoutComponentsRouteImport } from './routes/_layout/components'
import { Route as LayoutPipelinesIndexRouteImport } from './routes/_layout/pipelines.index'
import { Route as LayoutJobsIndexRouteImport } from './routes/_layout/jobs.index'
import { Route as LayoutAgentsIndexRouteImport } from './routes/_layout/agents.index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as LayoutWorkspacePipelineIdRouteImport } from './routes/_layout/workspace.$pipelineId'
import { Route as LayoutPipelinesJobsRouteImport } from './routes/_layout/pipelines.jobs'
import { Route as LayoutPipelinesPipelineIdRouteImport } from './routes/_layout/pipelines.$pipelineId'
import { Route as LayoutPipelinesOperationsIndexRouteImport } from './routes/_layout/pipelines.operations.index'
import { Route as LayoutPipelinesJobsIndexRouteImport } from './routes/_layout/pipelines.jobs.index'
import { Route as LayoutAgentsAgentIdIndexRouteImport } from './routes/_layout/agents.$agentId.index'
import { Route as LayoutPipelinesOperationsNewRouteImport } from './routes/_layout/pipelines.operations.new'
import { Route as LayoutPipelinesJobsJobIdRouteImport } from './routes/_layout/pipelines.jobs.$jobId'
import { Route as LayoutPipelinesOperationsOperationIdIndexRouteImport } from './routes/_layout/pipelines.operations.$operationId.index'
import { Route as LayoutPipelinesOperationsOperationIdEditRouteImport } from './routes/_layout/pipelines.operations.$operationId.edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiLocalSessionRoute = ApiLocalSessionRouteImport.update({
  id: '/api/local-session',
  path: '/api/local-session',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUsageRoute = LayoutUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillsRoute = LayoutSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPluginsRoute = LayoutPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPipelinesRoute = LayoutPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLocalAgentsRoute = LayoutLocalAgentsRouteImport.update({
  id: '/local-agents',
  path: '/local-agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConnectorsRoute = LayoutConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutComponentsRoute = LayoutComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPipelinesIndexRoute = LayoutPipelinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPipelinesRoute,
} as any)
const LayoutJobsIndexRoute = LayoutJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsIndexRoute = LayoutAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutWorkspacePipelineIdRoute =
  LayoutWorkspacePipelineIdRouteImport.update({
    id: '/workspace/$pipelineId',
    path: '/workspace/$pipelineId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPipelinesJobsRoute = LayoutPipelinesJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => LayoutPipelinesRoute,
} as any)
const LayoutPipelinesPipelineIdRoute =
  LayoutPipelinesPipelineIdRouteImport.update({
    id: '/$pipelineId',
    path: '/$pipelineId',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)
const LayoutPipelinesOperationsIndexRoute =
  LayoutPipelinesOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)
const LayoutPipelinesJobsIndexRoute =
  LayoutPipelinesJobsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutPipelinesJobsRoute,
  } as any)
const LayoutAgentsAgentIdIndexRoute =
  LayoutAgentsAgentIdIndexRouteImport.update({
    id: '/agents/$agentId/',
    path: '/agents/$agentId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPipelinesOperationsNewRoute =
  LayoutPipelinesOperationsNewRouteImport.update({
    id: '/operations/new',
    path: '/operations/new',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)
const LayoutPipelinesJobsJobIdRoute =
  LayoutPipelinesJobsJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => LayoutPipelinesJobsRoute,
  } as any)
const LayoutPipelinesOperationsOperationIdIndexRoute =
  LayoutPipelinesOperationsOperationIdIndexRouteImport.update({
    id: '/operations/$operationId/',
    path: '/operations/$operationId/',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)
const LayoutPipelinesOperationsOperationIdEditRoute =
  LayoutPipelinesOperationsOperationIdEditRouteImport.update({
    id: '/operations/$operationId/edit',
    path: '/operations/$operationId/edit',
    getParentRoute: () => LayoutPipelinesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/components': typeof LayoutComponentsRoute
  '/connectors': typeof LayoutConnectorsRoute
  '/local-agents': typeof LayoutLocalAgentsRoute
  '/pipelines': typeof LayoutPipelinesRouteWithChildren
  '/plugins': typeof LayoutPluginsRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills': typeof LayoutSkillsRoute
  '/usage': typeof LayoutUsageRoute
  '/api/local-session': typeof ApiLocalSessionRoute
  '/pipelines/$pipelineId': typeof LayoutPipelinesPipelineIdRoute
  '/pipelines/jobs': typeof LayoutPipelinesJobsRouteWithChildren
  '/workspace/$pipelineId': typeof LayoutWorkspacePipelineIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/agents/': typeof LayoutAgentsIndexRoute
  '/jobs/': typeof LayoutJobsIndexRoute
  '/pipelines/': typeof LayoutPipelinesIndexRoute
  '/pipelines/jobs/$jobId': typeof LayoutPipelinesJobsJobIdRoute
  '/pipelines/operations/new': typeof LayoutPipelinesOperationsNewRoute
  '/agents/$agentId/': typeof LayoutAgentsAgentIdIndexRoute
  '/pipelines/jobs/': typeof LayoutPipelinesJobsIndexRoute
  '/pipelines/operations/': typeof LayoutPipelinesOperationsIndexRoute
  '/pipelines/operations/$operationId/edit': typeof LayoutPipelinesOperationsOperationIdEditRoute
  '/pipelines/operations/$operationId/': typeof LayoutPipelinesOperationsOperationIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/components': typeof LayoutComponentsRoute
  '/connectors': typeof LayoutConnectorsRoute
  '/local-agents': typeof LayoutLocalAgentsRoute
  '/plugins': typeof LayoutPluginsRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills': typeof LayoutSkillsRoute
  '/usage': typeof LayoutUsageRoute
  '/api/local-session': typeof ApiLocalSessionRoute
  '/': typeof LayoutIndexRoute
  '/pipelines/$pipelineId': typeof LayoutPipelinesPipelineIdRoute
  '/workspace/$pipelineId': typeof LayoutWorkspacePipelineIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/agents': typeof LayoutAgentsIndexRoute
  '/jobs': typeof LayoutJobsIndexRoute
  '/pipelines': typeof LayoutPipelinesIndexRoute
  '/pipelines/jobs/$jobId': typeof LayoutPipelinesJobsJobIdRoute
  '/pipelines/operations/new': typeof LayoutPipelinesOperationsNewRoute
  '/agents/$agentId': typeof LayoutAgentsAgentIdIndexRoute
  '/pipelines/jobs': typeof LayoutPipelinesJobsIndexRoute
  '/pipelines/operations': typeof LayoutPipelinesOperationsIndexRoute
  '/pipelines/operations/$operationId/edit': typeof LayoutPipelinesOperationsOperationIdEditRoute
  '/pipelines/operations/$operationId': typeof LayoutPipelinesOperationsOperationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/_layout/components': typeof LayoutComponentsRoute
  '/_layout/connectors': typeof LayoutConnectorsRoute
  '/_layout/local-agents': typeof LayoutLocalAgentsRoute
  '/_layout/pipelines': typeof LayoutPipelinesRouteWithChildren
  '/_layout/plugins': typeof LayoutPluginsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/skills': typeof LayoutSkillsRoute
  '/_layout/usage': typeof LayoutUsageRoute
  '/api/local-session': typeof ApiLocalSessionRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/pipelines/$pipelineId': typeof LayoutPipelinesPipelineIdRoute
  '/_layout/pipelines/jobs': typeof LayoutPipelinesJobsRouteWithChildren
  '/_layout/workspace/$pipelineId': typeof LayoutWorkspacePipelineIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_layout/agents/': typeof LayoutAgentsIndexRoute
  '/_layout/jobs/': typeof LayoutJobsIndexRoute
  '/_layout/pipelines/': typeof LayoutPipelinesIndexRoute
  '/_layout/pipelines/jobs/$jobId': typeof LayoutPipelinesJobsJobIdRoute
  '/_layout/pipelines/operations/new': typeof LayoutPipelinesOperationsNewRoute
  '/_layout/agents/$agentId/': typeof LayoutAgentsAgentIdIndexRoute
  '/_layout/pipelines/jobs/': typeof LayoutPipelinesJobsIndexRoute
  '/_layout/pipelines/operations/': typeof LayoutPipelinesOperationsIndexRoute
  '/_layout/pipelines/operations/$operationId/edit': typeof LayoutPipelinesOperationsOperationIdEditRoute
  '/_layout/pipelines/operations/$operationId/': typeof LayoutPipelinesOperationsOperationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sign-up'
    | '/components'
    | '/connectors'
    | '/local-agents'
    | '/pipelines'
    | '/plugins'
    | '/settings'
    | '/skills'
    | '/usage'
    | '/api/local-session'
    | '/pipelines/$pipelineId'
    | '/pipelines/jobs'
    | '/workspace/$pipelineId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/agents/'
    | '/jobs/'
    | '/pipelines/'
    | '/pipelines/jobs/$jobId'
    | '/pipelines/operations/new'
    | '/agents/$agentId/'
    | '/pipelines/jobs/'
    | '/pipelines/operations/'
    | '/pipelines/operations/$operationId/edit'
    | '/pipelines/operations/$operationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sign-up'
    | '/components'
    | '/connectors'
    | '/local-agents'
    | '/plugins'
    | '/settings'
    | '/skills'
    | '/usage'
    | '/api/local-session'
    | '/'
    | '/pipelines/$pipelineId'
    | '/workspace/$pipelineId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/agents'
    | '/jobs'
    | '/pipelines'
    | '/pipelines/jobs/$jobId'
    | '/pipelines/operations/new'
    | '/agents/$agentId'
    | '/pipelines/jobs'
    | '/pipelines/operations'
    | '/pipelines/operations/$operationId/edit'
    | '/pipelines/operations/$operationId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/sign-up'
    | '/_layout/components'
    | '/_layout/connectors'
    | '/_layout/local-agents'
    | '/_layout/pipelines'
    | '/_layout/plugins'
    | '/_layout/settings'
    | '/_layout/skills'
    | '/_layout/usage'
    | '/api/local-session'
    | '/_layout/'
    | '/_layout/pipelines/$pipelineId'
    | '/_layout/pipelines/jobs'
    | '/_layout/workspace/$pipelineId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_layout/agents/'
    | '/_layout/jobs/'
    | '/_layout/pipelines/'
    | '/_layout/pipelines/jobs/$jobId'
    | '/_layout/pipelines/operations/new'
    | '/_layout/agents/$agentId/'
    | '/_layout/pipelines/jobs/'
    | '/_layout/pipelines/operations/'
    | '/_layout/pipelines/operations/$operationId/edit'
    | '/_layout/pipelines/operations/$operationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
  ApiLocalSessionRoute: typeof ApiLocalSessionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/local-session': {
      id: '/api/local-session'
      path: '/api/local-session'
      fullPath: '/api/local-session'
      preLoaderRoute: typeof ApiLocalSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/usage': {
      id: '/_layout/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof LayoutUsageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skills': {
      id: '/_layout/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof LayoutSkillsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/plugins': {
      id: '/_layout/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof LayoutPluginsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pipelines': {
      id: '/_layout/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof LayoutPipelinesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/local-agents': {
      id: '/_layout/local-agents'
      path: '/local-agents'
      fullPath: '/local-agents'
      preLoaderRoute: typeof LayoutLocalAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/connectors': {
      id: '/_layout/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof LayoutConnectorsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/components': {
      id: '/_layout/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof LayoutComponentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pipelines/': {
      id: '/_layout/pipelines/'
      path: '/'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof LayoutPipelinesIndexRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/jobs/': {
      id: '/_layout/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof LayoutJobsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents/': {
      id: '/_layout/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof LayoutAgentsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/workspace/$pipelineId': {
      id: '/_layout/workspace/$pipelineId'
      path: '/workspace/$pipelineId'
      fullPath: '/workspace/$pipelineId'
      preLoaderRoute: typeof LayoutWorkspacePipelineIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pipelines/jobs': {
      id: '/_layout/pipelines/jobs'
      path: '/jobs'
      fullPath: '/pipelines/jobs'
      preLoaderRoute: typeof LayoutPipelinesJobsRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/$pipelineId': {
      id: '/_layout/pipelines/$pipelineId'
      path: '/$pipelineId'
      fullPath: '/pipelines/$pipelineId'
      preLoaderRoute: typeof LayoutPipelinesPipelineIdRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/operations/': {
      id: '/_layout/pipelines/operations/'
      path: '/operations'
      fullPath: '/pipelines/operations/'
      preLoaderRoute: typeof LayoutPipelinesOperationsIndexRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/jobs/': {
      id: '/_layout/pipelines/jobs/'
      path: '/'
      fullPath: '/pipelines/jobs/'
      preLoaderRoute: typeof LayoutPipelinesJobsIndexRouteImport
      parentRoute: typeof LayoutPipelinesJobsRoute
    }
    '/_layout/agents/$agentId/': {
      id: '/_layout/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof LayoutAgentsAgentIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pipelines/operations/new': {
      id: '/_layout/pipelines/operations/new'
      path: '/operations/new'
      fullPath: '/pipelines/operations/new'
      preLoaderRoute: typeof LayoutPipelinesOperationsNewRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/jobs/$jobId': {
      id: '/_layout/pipelines/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/pipelines/jobs/$jobId'
      preLoaderRoute: typeof LayoutPipelinesJobsJobIdRouteImport
      parentRoute: typeof LayoutPipelinesJobsRoute
    }
    '/_layout/pipelines/operations/$operationId/': {
      id: '/_layout/pipelines/operations/$operationId/'
      path: '/operations/$operationId'
      fullPath: '/pipelines/operations/$operationId/'
      preLoaderRoute: typeof LayoutPipelinesOperationsOperationIdIndexRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
    '/_layout/pipelines/operations/$operationId/edit': {
      id: '/_layout/pipelines/operations/$operationId/edit'
      path: '/operations/$operationId/edit'
      fullPath: '/pipelines/operations/$operationId/edit'
      preLoaderRoute: typeof LayoutPipelinesOperationsOperationIdEditRouteImport
      parentRoute: typeof LayoutPipelinesRoute
    }
  }
}

interface LayoutPipelinesJobsRouteChildren {
  LayoutPipelinesJobsJobIdRoute: typeof LayoutPipelinesJobsJobIdRoute
  LayoutPipelinesJobsIndexRoute: typeof LayoutPipelinesJobsIndexRoute
}

const LayoutPipelinesJobsRouteChildren: LayoutPipelinesJobsRouteChildren = {
  LayoutPipelinesJobsJobIdRoute: LayoutPipelinesJobsJobIdRoute,
  LayoutPipelinesJobsIndexRoute: LayoutPipelinesJobsIndexRoute,
}

const LayoutPipelinesJobsRouteWithChildren =
  LayoutPipelinesJobsRoute._addFileChildren(LayoutPipelinesJobsRouteChildren)

interface LayoutPipelinesRouteChildren {
  LayoutPipelinesPipelineIdRoute: typeof LayoutPipelinesPipelineIdRoute
  LayoutPipelinesJobsRoute: typeof LayoutPipelinesJobsRouteWithChildren
  LayoutPipelinesIndexRoute: typeof LayoutPipelinesIndexRoute
  LayoutPipelinesOperationsNewRoute: typeof LayoutPipelinesOperationsNewRoute
  LayoutPipelinesOperationsIndexRoute: typeof LayoutPipelinesOperationsIndexRoute
  LayoutPipelinesOperationsOperationIdEditRoute: typeof LayoutPipelinesOperationsOperationIdEditRoute
  LayoutPipelinesOperationsOperationIdIndexRoute: typeof LayoutPipelinesOperationsOperationIdIndexRoute
}

const LayoutPipelinesRouteChildren: LayoutPipelinesRouteChildren = {
  LayoutPipelinesPipelineIdRoute: LayoutPipelinesPipelineIdRoute,
  LayoutPipelinesJobsRoute: LayoutPipelinesJobsRouteWithChildren,
  LayoutPipelinesIndexRoute: LayoutPipelinesIndexRoute,
  LayoutPipelinesOperationsNewRoute: LayoutPipelinesOperationsNewRoute,
  LayoutPipelinesOperationsIndexRoute: LayoutPipelinesOperationsIndexRoute,
  LayoutPipelinesOperationsOperationIdEditRoute:
    LayoutPipelinesOperationsOperationIdEditRoute,
  LayoutPipelinesOperationsOperationIdIndexRoute:
    LayoutPipelinesOperationsOperationIdIndexRoute,
}

const LayoutPipelinesRouteWithChildren = LayoutPipelinesRoute._addFileChildren(
  LayoutPipelinesRouteChildren,
)

interface LayoutRouteChildren {
  LayoutComponentsRoute: typeof LayoutComponentsRoute
  LayoutConnectorsRoute: typeof LayoutConnectorsRoute
  LayoutLocalAgentsRoute: typeof LayoutLocalAgentsRoute
  LayoutPipelinesRoute: typeof LayoutPipelinesRouteWithChildren
  LayoutPluginsRoute: typeof LayoutPluginsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSkillsRoute: typeof LayoutSkillsRoute
  LayoutUsageRoute: typeof LayoutUsageRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutWorkspacePipelineIdRoute: typeof LayoutWorkspacePipelineIdRoute
  LayoutAgentsIndexRoute: typeof LayoutAgentsIndexRoute
  LayoutJobsIndexRoute: typeof LayoutJobsIndexRoute
  LayoutAgentsAgentIdIndexRoute: typeof LayoutAgentsAgentIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutComponentsRoute: LayoutComponentsRoute,
  LayoutConnectorsRoute: LayoutConnectorsRoute,
  LayoutLocalAgentsRoute: LayoutLocalAgentsRoute,
  LayoutPipelinesRoute: LayoutPipelinesRouteWithChildren,
  LayoutPluginsRoute: LayoutPluginsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSkillsRoute: LayoutSkillsRoute,
  LayoutUsageRoute: LayoutUsageRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutWorkspacePipelineIdRoute: LayoutWorkspacePipelineIdRoute,
  LayoutAgentsIndexRoute: LayoutAgentsIndexRoute,
  LayoutJobsIndexRoute: LayoutJobsIndexRoute,
  LayoutAgentsAgentIdIndexRoute: LayoutAgentsAgentIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
  ApiLocalSessionRoute: ApiLocalSessionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
